name: Run tests

on:
  issue_comment:
    types: [created]

jobs:
  setup_and_test:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.comment.body == "test"
    outputs:
      pr_number: ${{ steps.get_pr_number.outputs.data }}
      pr_sha: ${{ fromJson(steps.fetch_pr_info.outputs.data).head.sha }}

    steps:
      - name: Get PR number
        id: get_pr_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "data=$PR_NUM" >> $GITHUB_OUTPUT

      - name: Fetch PR info
        id: fetch_pr_info
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pr}
          owner: nycolascruz
          repo: Automated-tests-with-Cypress
          pr: ${{ steps.get_pr_number.outputs.data }}
          mediaType: |
            format: raw

      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          status: pending
          context: Run tests
          sha: ${{ fromJson(steps.fetch_pr_info.outputs.data).head.sha }}

  run_tests:
    needs: setup_and_test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.setup_and_test.outputs.pr_sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.10.1
        with:
          start: npx vite --port 8000
          wait-on: "http://localhost:8000"
          record: true
          parallel: true
          group: PR-${{ needs.setup_and_test.outputs.pr_number }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

  final_status:
    needs: [setup_and_test, run_tests]
    runs-on: ubuntu-latest
    if: always() && github.event.issue.pull_request && github.event.comment.body == "test"

    steps:
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ needs.setup_and_test.outputs.pr_sha }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          status: ${{ contains(needs.*.result, 'failure') && "failure" || "success" }}
          context: Run tests
